<h1>Add</h1>
<?php
// if ($_SERVER["REQUEST_METHOD"] == "POST") {
//     // collect value of input field
//     $name = $_POST['username'];
//     if (empty($name)) {
//         echo "Name is empty";
//     } else {
//         echo $name;
//     }
// }
?>

<form method="POST" action="/admin/create">

	<fieldset>
		<legend>Legend</legend>

		<div class="form-group">
			<label for="username" class="form-label mt-4">Username</label>
			<input type="text" name="username" class="form-control" id="username" placeholder="Enter Username">

		</div>
		<div class="form-group">
			<label for="email" class="form-label mt-4">Email address</label>
			<input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp"
				placeholder="Enter email">
			<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
		</div>
		<div class="form-group">
			<label for="role" class="form-label mt-4">Role</label>
			<input type="text" class="form-control" name="role" id="role" aria-describedby="roleHelp"
				placeholder="Enter user role">
			<small id="roleHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
		</div>
		<button type="submit" class="btn btn-primary">Submit</button>
	</fieldset>
</form>